---
- name: Hello Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Say Hello
      ansible.builtin.debug:
        msg: "Hellooo AWXXX"
    - name: Pause for 5 seconds
      ansible.builtin.pause:
        seconds: 7
